### ISSUE TITLE
Error when combining with other javascript

### ISSUE THREAD

**Issue by trevorturk** [OscarGodson/jKey#5]
Everything works fine for me, except that when I combine my javascript files into one, I get this cryptic error:

http://grab.by/8zCA

Do you have any idea what might cause this? I had the same problem with jquery.hotkeys, which is why I wanted to try and use jkey. 

I'm using some custom javascript (so it may be my fault) and these:

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.4/jquery-ui.min.js"></script>

Any help would be very much appreciated. I'm really stuck.

**Comment by OscarGodson** [comment]
If it happened with jquery.hotkeys it's probably something with how you're combining your JS :)

If post your demo site on StackOverflow and they could probably help better, but from what I see, it _looks_ like it's not loading jQuery properly. It looks like it's sat jQuery is undefined of some sort? Or, it looks like .remove() is failing which also would be because jQuery isn't properly loaded.

Also, I can't see your code I think you posted after your text "and these:" :) Github doesn't allow html script tags in comments.

I'd post this on StackOverflow and then send me a link and maybe I can help out further! Going to close as this doesn't appear to be a bug with jKeys itself since you are having the same issue with jquery.hotkeys and the error doesn't appear to be related.

**Comment by trevorturk** [comment]
OK - thanks for the reply in any case!

**Comment by techwraith** [comment]
@oscargodson It's "itself" not "it's self" ;) #grammarnazi #whythehellamiusinghashtagshere?

**Comment by OscarGodson** [comment]
Haha, yes, you are #right

**Comment by trevorturk** [comment]
FWIW - I seem to be able to work around the issue by wrapping the plugin in document.ready... I'll let you know if/when I figure out the culprit, but this should work well enough. Very cool plugin. Thank you!

**Comment by OscarGodson** [comment]
Where are you putting your script tag?

**Comment by trevorturk** [comment]
This is the page:

https://app.teamlabhq.com/users/login

...and the js: 

https://app.teamlabhq.com/javascripts/all.js

I've added the document.ready and it's working now, but without the document.ready it was broken.

**Comment by OscarGodson** [comment]
I believe this might be because normally with all the scripts as separate script tags the browser wont pull this script down until jQuery is fully loaded and in this case jQuery isn't fully loaded and therefore you need a document ready to make sure all the scripts and CSS are done loading before trying to execute it. I'll look into this some more though. Thanks!
