### ISSUE TITLE
command-c triggers "c"

### ISSUE THREAD

**Issue by trevorturk** [OscarGodson/jKey#6]
When I press command-c, I get the "c" trigger. Is this a known behavior?

**Comment by OscarGodson** [comment]
Yes, this is a known limitation at this time. If you take a look at the docs at the bottom where it says "Important Notes!" the first item mentions this specifically. 

I'm currently working on a localization param so that you can modify certain keycodes (or all) to fit a different keyboard layout, but after that I was going to begin work on this issue. If you however know how to fix it or wanna take a stab at fixing it feel free to send me a pull request!

**Comment by trevorturk** [comment]
Aw - missed that! Sorry! I'm going to move back to jquery.hotkeys. I'm totally new to js stuff like this, so I'm useless. Thanks anyway!

**Comment by jjulian** [comment]
This was the killer issue for me - I recommend to use https://github.com/tzuryby/jquery.hotkeys

**Comment by OscarGodson** [comment]
Yeah, I suggest that too :) I haven't worked on this in a long time and I've been putting all my work into EpicEditor.
